@extends('layouts.admin')
@section('title','MS365 Accounts')
@section('page-title','MS365 Student Accounts')
@section('content')
<div class="page-header"><div><h2>MS365 Student Account Registry</h2><p>Only eligible email addresses in this registry can create Student Portal accounts.</p></div></div>
<div class="stats" style="margin-bottom:20px"><div class="stat"><span>Total imported</span><strong>{{ $statistics['total'] }}</strong></div><div class="stat"><span>Eligible</span><strong>{{ $statistics['eligible'] }}</strong></div><div class="stat"><span>Blocked</span><strong>{{ $statistics['blocked'] }}</strong></div></div>
<div class="card" style="margin-bottom:20px"><h3 style="margin-bottom:7px">Import Microsoft 365 CSV</h3><p style="margin-bottom:15px">Upload the Users CSV exported from Microsoft 365. Existing email records will be updated.</p><form method="POST" action="{{ route('admin.ms365-accounts.import') }}" enctype="multipart/form-data" style="display:flex;align-items:end;gap:12px;flex-wrap:wrap">@csrf<div style="flex:1;min-width:260px"><label for="csv_file">CSV file</label><input id="csv_file" class="input" type="file" name="csv_file" accept=".csv,text/csv" required>@error('csv_file')<span class="error">{{ $message }}</span>@enderror</div><button class="button" type="submit">Import CSV</button></form></div>
<div class="card"><form class="filters" method="GET" style="grid-template-columns:1fr auto"><input class="input" type="search" name="search" value="{{ $search }}" placeholder="Search name or MS365 email"><button class="button" type="submit">Search</button></form><div class="table-wrap"><table><thead><tr><th>Name</th><th>MS365 email</th><th>License</th><th>Status</th><th>Last imported</th></tr></thead><tbody>@forelse($accounts as $account)<tr><td><strong>{{ $account->display_name ?: '—' }}</strong></td><td>{{ $account->email }}</td><td>{{ $account->license ?: 'Not listed' }}</td><td>@if($account->soft_deleted_at)<span class="badge" style="color:#b42318">Soft deleted</span>@elseif($account->is_blocked)<span class="badge" style="color:#b42318">Blocked</span>@else<span class="badge">Eligible</span>@endif</td><td>{{ $account->last_imported_at?->format('M d, Y g:i A') ?: '—' }}</td></tr>@empty<tr><td colspan="5">No MS365 accounts have been imported.</td></tr>@endforelse</tbody></table></div><x-pagination :paginator="$accounts" label="MS365 account pages" /></div>
@endsection
